name: flutter_serial_communication
description: Library for serial communication. Currently supports Android USB (OTG) to communicate with Arduinos and other USB serial hardware on Android WITHOUT using root access.
version: 0.2.8
homepage: https://github.com/farellsujanto/flutter_serial_communication

environment:
  sdk: '>=2.19.5 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: id.farellsujanto.flutter_serial_communication
        pluginClass: FlutterSerialCommunicationPlugin
